Repository learn-able/learnable-fe, pull requests merged in 2020-05, with the labels that each got.

#26 Chore/setup context api
  mockData/mockData.js
  package.json
  pages/_app.js
  pages/index.js
  src/components/AddPlaylist/AddPlaylist.js
  src/components/Header/Header.js
  src/components/Input/Input.js
  src/components/PlaylistsContainer/PlaylistsContainer.js
  src/components/UserInfo/UserInfo.js
  src/contexts/playlistContext.js
  src/contexts/userContext.js
Labels: chore

#31 Chore/add playlist
  pages/index.js
  src/components/AddPlaylist/AddPlaylist.js
  src/components/Playlist/Playlist.js
  src/components/PlaylistViews/PlaylistView1.js
  src/components/PlaylistViews/PlaylistView2.js
  src/components/PlaylistViews/PlaylistView3.js
  src/components/PlaylistViews/PlaylistView4.js
  src/components/PlaylistsContainer/PlaylistsContainer.js
  src/contexts/playlistContext.js
  src/styles/GlobalStyles.js
Labels: chore

#32 Add theme styles. Update globalStyles. Add base styles to PlaylistsCo…
  pages/index.js
  src/components/AddPlaylist/AddPlaylist.js
  src/components/Playlist/Playlist.js
  src/components/PlaylistsContainer/PlaylistsContainer.js
  src/styles/GlobalStyles.js
  src/styles/theme.js
Labels: chore

#39 Complete progress bar
  src/components/PlaylistViews/PlaylistView3.js
  src/components/PlaylistViews/PlaylistView4.js
  src/components/ProgressBar/ProgressBar.js
Labels: feature

#42 Feature/input component
  package-lock.json
  package.json
  src/components/AddPlaylist/AddPlaylist.js
  src/components/Input/Input.js
  src/components/Input/InputStyles.js
  src/components/PlaylistsContainer/PlaylistsContainer.js
  src/hooks/useForm.js
  src/utils/validators.js
  yarn.lock
Labels: feature

#54 Discovery/initial flow
  mockData/mockData.js
  src/components/AddPlaylist/AddPlaylist.js
  src/components/DatePickerInput/DatePickerInput.js
  src/components/Input/Input.js
  src/components/NewPlaylistItemBar/NewPlaylistItemBar.js
  src/components/Playlist/Playlist.js
  src/components/PlaylistItem/PlaylistItem.js
  src/components/PlaylistItemContainer/PlaylistItemContainer.js
  src/components/PlaylistViews/PlaylistView1.js
  src/components/PlaylistViews/PlaylistView2.js
  src/components/PlaylistViews/PlaylistView3.js
  src/components/PlaylistViews/PlaylistView4.js
  src/contexts/playlistContext.js
  src/styles/theme.js
Labels: EPIC-playlist, feature
